const costPerDay = {
  Sedan: '5,500',
  SUV: '8,500',
  Hatchback: '6,500',
  Convertible: '15,000',
};

const cars = [
  {
    id: 1,
    make: 'Audi',
    type: 'Sedan',
    rating: 4.5,
    costPerDay: costPerDay['Sedan'],
    img: '/images/audiSe.jpeg',
    location: 'Kingston',
  },
  {
    id: 2,
    make: 'BMW',
    type: 'SUV',
    rating: 4.7,
    costPerDay: costPerDay['SUV'],
    img: '/images/bmwS.jpg',
    location: 'Kingston',
  },
  {
    id: 3,
    make: 'Nissan',
    type: 'Hatchback',
    rating: 4.3,
    costPerDay: costPerDay['Hatchback'],
    img: '/images/nissanH.jpeg',
    location: 'Spanish Town',
  },
  {
    id: 4,
    make: 'Toyota',
    type: 'Convertible',
    rating: 4.6,
    costPerDay: costPerDay['Convertible'],
    img: '/images/toyotaC.webp',
    location: 'Montego Bay',
  },
  {
    id: 5,
    make: 'Honda',
    type: 'Sedan',
    rating: 4.4,
    costPerDay: costPerDay['Sedan'],
    img: '/images/hondaSe.jpeg',
    location: 'Kingston',
  },
  {
    id: 6,
    make: 'Mitsubishi',
    type: 'SUV',
    rating: 4.5,
    costPerDay: costPerDay['SUV'],
    img: '/images/mitsuS.jpeg',
    location: 'Ocho Rios',
  },
  {
    id: 7,
    make: 'Subaru',
    type: 'Hatchback',
    rating: 4.2,
    costPerDay: costPerDay['Hatchback'],
    img: '/images/subaruH.webp',
    location: 'Kingston',
  },
  {
    id: 8,
    make: 'Audi',
    type: 'Convertible',
    rating: 4.8,
    costPerDay: costPerDay['Convertible'],
    img: '/images/audiC.jpeg',
    location: 'Spanish Town',
  },
  {
    id: 9,
    make: 'BMW',
    type: 'Sedan',
    rating: 4.6,
    costPerDay: costPerDay['Sedan'],
    img: '/images/bmwSe.jpg',
    location: 'Kingston',
  },
  {
    id: 10,
    make: 'Toyota',
    type: 'SUV',
    rating: 4.5,
    costPerDay: costPerDay['SUV'],
    img: '/images/toyotaS.webp',
    location: 'Spanish Town',
  },
  {
    id: 11,
    make: 'Honda',
    type: 'Hatchback',
    rating: 4.3,
    costPerDay: costPerDay['Hatchback'],
    img: '/images/hondaH.jpeg',
    location: 'Ocho Rios',
  },
  {
    id: 12,
    make: 'Nissan',
    type: 'Convertible',
    rating: 4.7,
    costPerDay: costPerDay['Convertible'],
    img: '/images/nissanC.webp',
    location: 'Montego Bay',
  },
  {
    id: 13,
    make: 'Mitsubishi',
    type: 'Sedan',
    rating: 4.4,
    costPerDay: costPerDay['Sedan'],
    img: '/images/mitsuSe.jpeg',
    location: 'Kingston',
  },
  {
    id: 14,
    make: 'Subaru',
    type: 'SUV',
    rating: 4.5,
    costPerDay: costPerDay['SUV'],
    img: '/images/subaruS.jpg',
    location: 'St. Elizabeth',
  },
  {
    id: 15,
    make: 'Audi',
    type: 'Hatchback',
    rating: 4.6,
    costPerDay: costPerDay['Hatchback'],
    img: '/images/audiH.jpeg',
    location: 'Montego Bay',
  },
  {
    id: 16,
    make: 'BMW',
    type: 'Convertible',
    rating: 4.8,
    costPerDay: costPerDay['Convertible'],
    img: '/images/bmwC.jpeg',
    location: 'Kingston',
  },
];

export default cars;
